export enum Role {
  COLABORADOR = 'COLABORADOR',
  GESTOR = 'GESTOR',
  ANALISTA_TI = 'ANALISTA_TI',
  AUDITOR = 'AUDITOR',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ATIVO = 'ATIVO',
  INATIVO = 'INATIVO',
}

export enum TicketStatus {
  RASCUNHO = 'RASCUNHO',
  AGUARDANDO_APROVACAO = 'AGUARDANDO_APROVACAO',
  APROVADO = 'APROVADO',
  EM_PROCESSAMENTO = 'EM_PROCESSAMENTO',
  CONCLUIDO = 'CONCLUIDO',
  REJEITADO = 'REJEITADO',
  CANCELADO = 'CANCELADO',
  FALHA_INTEGRACAO = 'FALHA_INTEGRACAO',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  CANCEL = 'CANCEL',
  REPROCESS = 'REPROCESS',
  IMPORT_CSV = 'IMPORT_CSV',
  CASI_CALL = 'CASI_CALL',
  CONFIG_CHANGE = 'CONFIG_CHANGE',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
}
